site_name: Helmless
site_description: Deploy containers to Google Cloud Run with Helm's, avoiding the complexity of Kubernetes and Terraform.
site_url: https://helmless.io
repo_url: https://github.com/helmless/helmless
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - What is Helmless?:
      - what-is-helmless.md
      - Architecture: architecture.md
  - Documentation:
      - docs/index.md
      - Google CloudRun:
          - docs/cloudrun/index.md
          - Getting Started: docs/cloudrun/getting-started.md
          - CI/CD: docs/cloudrun/ci-cd.md
          - Examples: docs/cloudrun/examples.md
          - Advanced Infrastructure: docs/cloudrun/advanced.md
          - Chart Schema: docs/cloudrun/schema/values.md
plugins:
  - privacy
  - search
  - minify:
      minify_html: true
  - multirepo:
      cleanup: false
      keep_docs_dir: false
      nav_repos:
        - name: docs
          import_url: 'https://github.com/helmless/google-cloudrun-chart?branch=main'
          imports: ['cloudrun/schema/*.md']

  - redirects:
      redirect_maps:
        'cloudrun/index.md': 'docs/cloudrun/getting-started.md'
        'cloudrun/getting-started/index.md': 'docs/cloudrun/getting-started.md'
        'getting-started/index.md': 'docs/cloudrun/getting-started.md'
theme:
  name: material
  custom_dir: docs/_overrides/
  palette:
    scheme: slate
    primary: custom
    accent: light blue
  icon:
    logo: material/rocket-launch
    repo: material/github
    annotation: material/chevron-right-circle
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
extra:
  generator: false
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-1ZHVXV2WWV
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  font:
    text:
      - family: Inter
      - url: https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap
    code:
      - family: JetBrains Mono
      - url: https://fonts.googleapis.com/css2?family=JetBrains+Mono&display=swap
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_css:
  - assets/stylesheets/extra.css
