name: 🚀 Deploy to Google Cloud Run

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  deploy:
    name: 🚀 example-app
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🔑 Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_POOL }} # The Google Cloud Workload Identity Pool to use for authentication

      - name: 📜 Template Helmless Chart
        uses: helmless/action@v0.1.0
        with:
          files: examples/minimal-service/values.yaml

      - name: 🚀 Deploy Service
        uses: helmless/google-cloudrun-deploy-action@v0.1.0
        id: deploy
        with:
          gcp_project: ${{ secrets.GCP_PROJECT_ID }} # The Google Cloud project to deploy to
          dry_run: false # setting this to true will validate the template against the Google Cloud Run API, but not deploy
